---
title: "2 Processing"
author: "Adriano Rutz"
creative_commons: CC BY-SA
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
opengraph:
    image:
      src: https://github.com/adafede/cascade/blob/main/man/figures/logo.svg
      alt: "Contextualizing untargeted Annotation with Semi-quantitative Charged Aerosol Detection for pertinent characterization of natural Extracts"
    twitter:
      creator: "@adafede"
vignette: >
  %\VignetteIndexEntry{2 Processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_knit$set(root.dir = system.file(package = "cascade"))
```

```{r cascade, include = FALSE}
library("cascade")
```

This vignette describes some of the processing functions.
It assumes you already checked the [previous steps](https://adafede.github.io/cascade/articles/I-basics.html).

## Compare peaks to features

This assumes you previously generated the necessary mzmine features' table.

```{r check-alignment-default, warning=FALSE, out.width="100%"}
process_compare_peaks(show_example = TRUE)
```

Development follows.
