---
title: 4 Visualizing raw TIMA results
author:
  name: Adriano Rutz
  orcid: 0000-0003-0443-9902
citation:
  url: https://adafede.github.io/cascade/vignettes/articles/IV-tima.html
comments:
  giscus:
    repo: adafede/cascade
  hypothesis:
    showHighlights: always
creative_commons: CC BY
date: today
format:
  html:
    smooth-scroll: true
google-scholar: true
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
lang: en
license: CC BY
opengraph:
  image:
    src: https://github.com/adafede/cascade/blob/main/man/figures/logo.svg
    alt: Contextualizing untargeted Annotation with Semi-quantitative Charged
      Aerosol Detection for pertinent characterization of natural Extracts
vignette: >
  %\VignetteIndexEntry{4 TIMA}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| label: cascade
#| include: false

library("cascade")
```

This vignette describes additional helper functions to visualize
[TIMA](https://taxonomicallyinformedannotation.github.io/tima/) results.

## Visualization

To check the full results:

```{r}
#| label: tima-plots
#| message: false
#| warning: false

plots <- cascade::prepare_tima_annotations(
  show_example = TRUE
) |>
  cascade::plot_tima()
# cascade::prepare_tima_annotations(
#   annotations = list(
#     "yourExperiment1"="PathToYourTimaOutput1",
#     "yourExperiment2"="PathToYourTimaOutput2"
#     )
# ) |>
#   cascade::plot_tima()
```

```{r}
#| label: tima-plots-h
#| message: false
#| warning: false
#| fig-height: 9
#| dev: svglite

plots$histogram
```

```{r}
#| label: tima-plots-t
#| message: false
#| warning: false
#| dev: svglite

plots$treemap
```

```{r}
#| label: tima-plots-s
#| message: false
#| warning: false
#| dev: svglite

plots$sunburst
```

To compare annotated and predicted classes:

```{r}
#| label: tima-plots-1
#| warning: false
#| fig-height: 12
#| dev: svglite

list(
  cascade::prepare_tima_annotations(
    show_example = TRUE
  ),
  cascade::prepare_tima_annotations(
    show_example = TRUE,
    predicted_classes = TRUE
  )
) |>
  tidytable::bind_rows() |>
  list() |>
  cascade::plot_tima() |>
  purrr::pluck("histogram")
```

To compare different filtering thresholds:

```{r}
#| label: tima-plots-2
#| warning: false
#| fig-height: 10
#| dev: svglite

list(
  cascade::prepare_tima_annotations(
    show_example = TRUE
  ),
  cascade::prepare_tima_annotations(
    show_example = TRUE,
    min_score_biological = 0.2,
    min_score_final = 0.4
  ),
  cascade::prepare_tima_annotations(
    show_example = TRUE,
    min_score_initial = 0.2,
    min_score_biological = 0.2,
    min_score_chemical = 0.2,
    min_score_final = 0.4,
    min_matched_peaks_absolute = 6L,
    min_matched_peaks_percentage = 0.5,
    min_peaks = 10L
  )
) |>
  tidytable::bind_rows() |>
  list() |>
  cascade::plot_tima() |>
  purrr::pluck("histogram")
```

We hope you enjoyed using **CASCADE** and are pleased to hear from you!

For any remark or suggestion, please [fill an
issue](https://github.com/adafede/cascade/issues) or feel free to contact us
directly.
