filename:
  # mzml: M_[0-9]{2}_01
  # mzml: 191109_AR_10043_enriched_UHR_Pos
  mzml:
    # pos: 191109_AR_10043_enriched_UHR_Pos
    # neg: 191109_AR_10043_enriched_UHR_Neg
    pos: 210619_AR_06_V_03_2_01
    neg: 210619_AR_03_V_03_2_01_NEG
  annotation:
    tima:
      pos: 191109_AR_10043_enriched_UHR_Pos.tsv.gz
      neg: 191109_AR_10043_enriched_UHR_Neg.tsv.gz
annotation:
  mode:
    neg: TRUE
    pos: TRUE
  confidence:
    min: 0.4
  tool: tima
chromato:
  intensity:
    ms1:
      min: 10000
      max: 1000000000
    ms2:
      min: 10000
      max: 1000000000
  occurrence:
    min: 1
    max: 50
  peak:
    similarity:
      prefilter: 0.6
      filter: 0.8
    tolerance:
      rt: 0.15
      ppm: 10
    area:
      min: 0.005
  shift:
    # cad: 0.055 # old
    # pda: 0.090 # old
    cad: 0.065 # new
    pda: 0.080 # new
  time:
    min: 0.7
    max: 35.2
signal:
  detector:
    bpi: FALSE
    cad: TRUE
    pda: FALSE
  fourrier:
    components: 0.01
  frequency: 2
  resample: 1
  sigma: 0.05
  k2: 250
  k4: 1250000
  smoothing: 8
  baseline: 0
structures:
  dimensionality: 2
  min: 25
  level: structure_taxonomy_npclassifier_03class
  c18: TRUE
  mass:
    min: 150
    max: 1500
  logp:
    min: -1
    max: 6
organisms:
  level: organism_taxonomy_05order
  taxon: Gentianales # let empty for no filter
  group: organism_taxonomy_08genus
  subgroup: organism_taxonomy_09species
  wikidata:
    # Asteraceae: Q25400
    # Simaroubaceae: Q156679
    # Gentianaceae: Q157216
    # Picrasma: Q135638
    # Picrasma quassioides: Q855778
    Swertia: Q163970
    # Swertia chirayita: Q21318003
    # Gentiana: Q144682
    # Gentiana lutea: Q158572
    # Quassia: Q1947702
    # Quassia amara: Q135389
    # Aloe: Q127134
    # Aloe ferox: Q1194889
    # Sambucus nigra: Q22701
    # Coriandrum sativum: Q41611
    # Juniperus communis: Q26325
    # Piper cubeba: Q161927
    # Aframomum melegueta: Q1503476
    # Angelica archangelica: Q207745
    # Glycyrrhiza glabra: Q257106
    # Cinnamomum cassia: Q204148
    # Iris pallida: Q161347
    # Centaurea benedicta: Q792835
    # Hypericum perforatum: Q158289
    # Prunus dulcis: Q39918
    # Taraxacum officinale: Q131219
    # Rheum palmatum: Q1109580
    # Arnica montana: Q207848
    # Cinchona succirubra: Q50830790
    # # Cinchona pubescens: Q164574
    # Ginkgo biloba: Q43284
    # Panax ginseng: Q182881
    # Salvia officinalis: Q1111359
    # Orchidaceae: Q25308
  comparison:
    # - Arnica montana
    # - Cinchona succirubra
    # - Ginkgo biloba
    # - Panax ginseng
    # - Salvia officinalis
    - Swertia
    - SwertiaExp
references:
  date:
    start: 1900
    end: 2023
queries:
  limit: 50000
workers: 10
misc:
  solubility:
    limit: 58
force: FALSE
