on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cascade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env create --file environment.yml
      - name: Run tests
        run: |
          bash tests/integration_test.sh
