---
name: External Use

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"
  workflow_dispatch:

permissions: read-all

jobs:
  cascade-test:
    name: cascade-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: ${{ steps.cpu-cores.outputs.count }}
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev libnetcdf-dev \
          && sudo apt-get clean \
          && sudo rm -rf /var/lib/apt/lists/*
      - name: Install
        run: |
          install.packages("cascade", repos = c("https://adafede.r-universe.dev", "https://bioc.r-universe.dev", "https://cloud.r-project.org"))
        shell: Rscript {0}
      - name: Run pipeline
        run: |
          cascade::check_chromatograms_alignment(show_example = TRUE)
          cascade::check_peaks_integration(show_example = TRUE)
          cascade::process_compare_peaks(show_example = TRUE)
          cascade::generate_pseudochromatograms(show_example = TRUE)
          cascade::generate_ids()
          cascade::generate_tables()
        shell: Rscript {0}
